### ISSUE TITLE
trying to get a list of all folders and jobs

### ISSUE THREAD

**Issue by adclose** [controlm/integrations-plugins-community-solutions#1]
I'm trying to get a list of all folders and jobs on a server.  I'm been able to use the rest API to do some other basic stuff but haven't managed this.   I'm thinking it might be a server issue but was hoping you could help
This is my url useing a GET
{{baseUrl}}/deploy/jobs?format=json&folder=*&ctm=CTMQA
Auth is working fine but get. 

{
    "errors": [
        {
            "message": "Failed to get Folder data from control-m CTMQA (folder: *) . Folder is not Smart. Exporting a non-Smart folder is not supported"
        }
    ]
}

Aaron

PS if anyone wants it I've pulled the whole swagger doc into a postman collection
@JoeGoldberg

**Comment by adclose** [comment]
Thanks I'll see if we can get it updated

I appreciate your help.

Aaron

**Comment by JoeGoldberg** [comment]
Hi Aaron,

Please let me know if there’s anything el sei can do.

It would be great t hear what your plans are for using Automation API, json, etc. and any details you are willing to provide about any use cases or scenarios you are considering.

________________________________
Best regards,
Joe Goldberg
Evangelist
Digital Business Automation
Direct

+1 416.722.5672
14 Stonedene Blvd..
North York, Ontario M2R 3C7
Canada
[BMC Communities]<https://communities.bmc.com/>
[Twitter]<https://twitter.com/bmcsoftware>
[Facebook]<https://www.facebook.com/bmcsoftware>
[YouTube]<http://www.youtube.com/user/BMCSoftwareBMCtv>
[LinkedIn]<http://www.linkedin.com/company/bmc-software>

[BMC—Run and Reinvent]<http://www.bmc.com/>


From: Aaron Close ***@***.***>
Sent: Monday, May 10, 2021 3:59 PM
To: controlm/integrations-plugins-community-solutions ***@***.***>
Cc: Goldberg, Joe ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [controlm/integrations-plugins-community-solutions] trying to get a list of all folders and jobs (#1)


Thanks I'll see if we can get it updated

I appreciate your help.

Aaron
