### ISSUE TITLE
How to define a Dataflow job 

### ISSUE THREAD

**Issue by JoeGoldberg** [controlm/integrations-plugins-community-solutions#25]
I have a Dataflow job that runs successfully when using GCLOUD but fails as a Control-M job. Please let me know what I'm doing wrong.

The GCLOUD command that works:

"gcloud dataflow jobs run jogoldbe-BQ-dataload-job000 --gcs-location gs://dataflow-templates-us-central1/latest/GCS_Text_to_BigQuery --region us-central1 --num-workers 2 --staging-location gs://prj1968-bmc-data-platform-foundation/bmc_transactions/tmp20/ --parameters javascriptTextTransformGcsPath=gs://prj1968-bmc-data-platform-foundation/bmc_transaction_details/bmc_transaction_details_transform.js,JSONPath=gs://prj1968-bmc-data-platform-foundation/bmc_transaction_details/bmc_transactions_schema.json,javascriptTextTransformFunctionName=transform,outputTable=sso-gcp-dba-ctm4-pub-cc10274:bmc_dataplatform_foundation.bmc_transaction_details_v2,inputFilePattern=gs://prj1968-bmc-data-platform-foundation/bmc_transaction_details/bmc_transaction_details.csv,bigQueryLoadingTemporaryDirectory=gs://prj1968-bmc-data-platform-foundation/bmc_transactions/tmp10/"

I am trying to translate that into a Dataflow job but job failing with these errors:
Extracted runtime parameter:
----------------------------
'ERRORCODE'==> '400' 
'REASON_FOR_FAILURE'==> 'Invalid JSON payload received. Unknown name "javascriptTextTransformGcsPath" at 'launch_parameters': Canno\
t find field.
Invalid JSON payload received. Unknown name "JSONPath" at 'launch_parameters': Cannot find field.
Invalid JSON payload received. Unknown name "javascriptTextTransformFunctionName" at 'launch_parameters': Cannot find field.
Invalid JSON payload received. Unknown name "outputTable" at 'launch_parameters': Cannot find field.
Invalid JSON payload received. Unknown name "inputFilePattern" at 'launch_parameters': Cannot find field.
Invalid JSON payload received. Unknown name "bigQueryLoadingTemporaryDirectory" at 'launch_parameters': Cannot find field.' 

This is what the job looks like (defined in Workload Automation client and exported via ctm deploy jobs::get):

{
  "jog-gcp-data-foundation": {
    "Type": "Folder",
    "ControlmServer": "smprod",
    "OrderMethod": "Manual",
    "ActiveRetentionPolicy": "CleanEndedOK",
    "SiteStandard": "jog",
    "SubApplication": "data-foundation",
    "CreatedBy": "jogoldbe",
    "Application": "gcp",
    "When": {
      "RuleBasedCalendars": {
        "Included": [
          "EVERYDAY"
        ],
        "EVERYDAY": {
          "Type": "Calendar:RuleBased",
          "When": {
            "DaysRelation": "OR",
            "WeekDays": [
              "NONE"
            ],
            "MonthDays": [
              "ALL"
            ]
          }
        }
      }
    },
    "jog-dataflow-job001": {
      "Type": "Job:ApplicationIntegrator:AI Google DataFlow",
      "AI-Location": "us-central1",
      "AI-Parameters (JSON Format)": "{\"jobName\":\"jog-dataflow-job000\",\"javascriptTextTransformGcsPath\":\"gs://prj1968-bmc-data-platform-foundation/bmc_transaction_details/bmc_transaction_details_transform.js\",\"JSONPath\":\"gs://prj1968-bmc-data-platform-foundation/bmc_transaction_details/bmc_transactions_schema.json\",\"javascriptTextTransformFunctionName\":\"transform\",\"outputTable\":\"sso-gcp-dba-ctm4-pub-cc10274:bmc_dataplatform_foundation.bmc_transaction_details_v2\",\"inputFilePattern\":\"gs://prj1968-bmc-data-platform-foundation/bmc_transaction_details/bmc_transaction_details.csv\",\"bigQueryLoadingTemporaryDirectory\":\"gs://prj1968-bmc-data-platform-foundation/bmc_transactions/tmp10/\"}",
      "AI-Log Level": "INFO",
      "AI-Template Location (gs://)": "gs://dataflow-templates-us-central1/latest/GCS_Text_to_BigQuery",
      "AI-Project ID": "sso-gcp-dba-ctm4-pub-cc10274",
      "AI-Template Type": "Classic Template",
      "ConnectionProfile": "DFLOW-631873438236",
      "SubApplication": "data-foundation",
      "Host": "ip-172-31-20-153.us-west-2.compute.internal",
      "CreatedBy": "jogoldbe",
      "RunAs": "DFLOW-631873438236",
      "Application": "gcp",
      "Variables": [
        {
          "UCM-BC_COUNTER": "6"
        }
      ],
      "When": {
        "WeekDays": [
          "NONE"
        ],
        "MonthDays": [
          "ALL"
        ],
        "DaysRelation": "OR"
      }
    }
  }
}

**Comment by neilcu** [comment]
Solved by including environment parameters that were generated in the JSON.
